FROM directus/directus:10.12.1

USER root
RUN corepack enable
USER node

RUN pnpm install directus-extension-sync

# copy all files in email-templates to /templates/
COPY ./email-templates/ /directus/email-templates/

# RUN pnpm install directus-extension-schema-sync
# This is for when building for production
# COPY ./schema-sync ./schema-sync
