version: "3"

networks:
  directus-net:
  # Only required when running behind a reverse proxy like nginx-proxy: I use this one https://github.com/evertramos/nginx-proxy-automation?tab=readme-ov-file
  # nginx-net:
  #   external:
  #     name: nginx-net

services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - directus-net
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 64831:5432

  cache:
    image: redis:6
    restart: always
    networks:
      - directus-net

  directus:
    # image: directus/directus:10.10.4
    build:
      context: ./
      dockerfile: Dockerfile.directus
    restart: always
    ports:
      - 8055:8055
    volumes:
      - ./directus-uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    networks:
      - directus-net
      # - nginx-net
    environment:
      KEY: "${KEY}"
      SECRET: "${SECRET}"
      WEBSOCKETS_ENABLED: "true"
      SCHEMA_SYNC: "BOTH"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"

      CACHE_ENABLED: "false"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"
      IMPORT_IP_DENY_LIST: ""

      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

#      PUBLIC_URL: "${PUBLIC_URL}"

      # CORS FOR LOCALHOST
      CORS_ENABLED: "true"
      CORS_ORIGIN: "${CORS_ORIGIN}"
      CORS_METHODS: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
      CORS_ALLOWED_HEADERS: "Content-Type, Authorization, X-Requested-With"
      CORS_EXPOSED_HEADERS: "Content-Range, X-Content-Range"


#  frontend:
#    depends_on:
#      - directus
#    restart: "unless-stopped"
##    networks:
##      - nginx-net
#    build:
#      context: ./
#      dockerfile: Dockerfile.frontend
#    env_file:
#      - .env
#    environment:
#      # Only required when running behind a reverse proxy like nginx-proxy
#      VIRTUAL_HOST: "${VIRTUAL_HOST}"
#      VIRTUAL_PORT: "${VIRTUAL_PORT}"
#      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}"
#      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
#    ports:
#      - 8001:80


volumes:
  postgres_data:

